spring:
  flyway:
    locations:
      - classpath:db/migration
  datasource:
    url: jdbc:mysql://localhost:/crud?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect